# Generated by Django 4.0.1 on 2022-03-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blooddonation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='email',
            field=models.EmailField(default=False, max_length=254),
        ),
        migrations.AddField(
            model_name='donor',
            name='email',
            field=models.EmailField(default=False, max_length=254),
        ),
    ]
