# Generated by Django 4.0.1 on 2022-02-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blooddonation', '0002_alter_donor_phone_number_alter_user_is_center_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='phone_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='phone_number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
