# Generated by Django 4.0.1 on 2022-05-05 15:56

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('blooddonation', '0002_center_email_donor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='blood_group',
            field=models.CharField(choices=[('AP', 'A+'), ('AM', 'A-'), ('BP', 'B+'), ('BM', 'B-'), ('ABP', 'AB+'), ('ABM', 'AB-'), ('OP', 'O+'), ('OM', 'O-')], default='A+', max_length=20),
        ),
        migrations.AlterField(
            model_name='center',
            name='location',
            field=location_field.models.plain.PlainLocationField(max_length=63),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
