# Generated by Django 4.0.1 on 2022-05-08 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blooddonation', '0004_profile_facebok_profile_instagram_profile_twitter_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='facebok',
            new_name='facebook',
        ),
    ]
