# Generated by Django 4.0.1 on 2022-05-08 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blooddonation', '0005_rename_facebok_profile_facebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='host',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='host', to='blooddonation.center'),
        ),
    ]
