# Generated by Django 4.0.1 on 2022-05-09 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blooddonation', '0006_event_host'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='country',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='user',
        ),
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='donation_type',
            field=models.CharField(choices=[('Whole blood', 'Whole blood'), ('Placelet', 'Placelet'), ('Power red', 'Power red'), ('', '')], default='Whole blood', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='center',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='center', to='blooddonation.center'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='A+', max_length=20),
        ),
    ]
